import type { Book } from './types';

export const BIBLE_BOOKS: Book[] = [
    { name: 'Genesis', koreanName: '창세기', chapters: 50 },
    { name: 'Exodus', koreanName: '출애굽기', chapters: 40 },
    { name: 'Leviticus', koreanName: '레위기', chapters: 27 },
    { name: 'Numbers', koreanName: '민수기', chapters: 36 },
    { name: 'Deuteronomy', koreanName: '신명기', chapters: 34 },
    { name: 'Joshua', koreanName: '여호수아', chapters: 24 },
    { name: 'Judges', koreanName: '사사기', chapters: 21 },
    { name: 'Ruth', koreanName: '룻기', chapters: 4 },
    { name: '1 Samuel', koreanName: '사무엘상', chapters: 31 },
    { name: '2 Samuel', koreanName: '사무엘하', chapters: 24 },
    { name: '1 Kings', koreanName: '열왕기상', chapters: 22 },
    { name: '2 Kings', koreanName: '열왕기하', chapters: 25 },
    { name: '1 Chronicles', koreanName: '역대상', chapters: 29 },
    { name: '2 Chronicles', koreanName: '역대하', chapters: 36 },
    { name: 'Ezra', koreanName: '에스라', chapters: 10 },
    { name: 'Nehemiah', koreanName: '느헤미야', chapters: 13 },
    { name: 'Esther', koreanName: '에스더', chapters: 10 },
    { name: 'Job', koreanName: '욥기', chapters: 42 },
    { name: 'Psalms', koreanName: '시편', chapters: 150 },
    { name: 'Proverbs', koreanName: '잠언', chapters: 31 },
    { name: 'Ecclesiastes', koreanName: '전도서', chapters: 12 },
    { name: 'Song of Solomon', koreanName: '아가', chapters: 8 },
    { name: 'Isaiah', koreanName: '이사야', chapters: 66 },
    { name: 'Jeremiah', koreanName: '예레미야', chapters: 52 },
    { name: 'Lamentations', koreanName: '예레미야애가', chapters: 5 },
    { name: 'Ezekiel', koreanName: '에스겔', chapters: 48 },
    { name: 'Daniel', koreanName: '다니엘', chapters: 12 },
    { name: 'Hosea', koreanName: '호세아', chapters: 14 },
    { name: 'Joel', koreanName: '요엘', chapters: 3 },
    { name: 'Amos', koreanName: '아모스', chapters: 9 },
    { name: 'Obadiah', koreanName: '오바댜', chapters: 1 },
    { name: 'Jonah', koreanName: '요나', chapters: 4 },
    { name: 'Micah', koreanName: '미가', chapters: 7 },
    { name: 'Nahum', koreanName: '나훔', chapters: 3 },
    { name: 'Habakkuk', koreanName: '하박국', chapters: 3 },
    { name: 'Zephaniah', koreanName: '스바냐', chapters: 3 },
    { name: 'Haggai', koreanName: '학개', chapters: 2 },
    { name: 'Zechariah', koreanName: '스가랴', chapters: 14 },
    { name: 'Malachi', koreanName: '말라기', chapters: 4 },
    { name: 'Matthew', koreanName: '마태복음', chapters: 28 },
    { name: 'Mark', koreanName: '마가복음', chapters: 16 },
    { name: 'Luke', koreanName: '누가복음', chapters: 24 },
    { name: 'John', koreanName: '요한복음', chapters: 21 },
    { name: 'Acts', koreanName: '사도행전', chapters: 28 },
    { name: 'Romans', koreanName: '로마서', chapters: 16 },
    { name: '1 Corinthians', koreanName: '고린도전서', chapters: 16 },
    { name: '2 Corinthians', koreanName: '고린도후서', chapters: 13 },
    { name: 'Galatians', koreanName: '갈라디아서', chapters: 6 },
    { name: 'Ephesians', koreanName: '에베소서', chapters: 6 },
    { name: 'Philippians', koreanName: '빌립보서', chapters: 4 },
    { name: 'Colossians', koreanName: '골로새서', chapters: 4 },
    { name: '1 Thessalonians', koreanName: '데살로니가전서', chapters: 5 },
    { name: '2 Thessalonians', koreanName: '데살로니가후서', chapters: 3 },
    { name: '1 Timothy', koreanName: '디모데전서', chapters: 6 },
    { name: '2 Timothy', koreanName: '디모데후서', chapters: 4 },
    { name: 'Titus', koreanName: '디도서', chapters: 3 },
    { name: 'Philemon', koreanName: '빌레몬서', chapters: 1 },
    { name: 'Hebrews', koreanName: '히브리서', chapters: 13 },
    { name: 'James', koreanName: '야고보서', chapters: 5 },
    { name: '1 Peter', koreanName: '베드로전서', chapters: 5 },
    { name: '2 Peter', koreanName: '베드로후서', chapters: 3 },
    { name: '1 John', koreanName: '요한1서', chapters: 5 },
    { name: '2 John', koreanName: '요한2서', chapters: 1 },
    { name: '3 John', koreanName: '요한3서', chapters: 1 },
    { name: 'Jude', koreanName: '유다서', chapters: 1 },
    { name: 'Revelation', koreanName: '요한계시록', chapters: 22 }
];